
**IVP LAB EXAM**

Name: Aditya Kamath

Roll no.: C021 

Semester: VI 

Program: B.Tech

Branch: EXTC

Date of performance: 9/4/21

Link for the file:
https://colab.research.google.com/drive/1Odi-jlXrU3Ep8MgWsQFmkxy9CAdB43G4?usp=sharing

In [ ]:
#Importing all The Packages we used in this Experiment
import cv2
import numpy as np

# Task 2

In [ ]:
# Create 8x8 random matrix
x = 8
y = 8
A = np.random.randint(0,16,size=(x,y))
print(A)

[[ 7 10  9  2 14 11  8  1]
 [ 5  0  6  9  3 11 15  8]
 [ 1  7 12  1  3 15  1 11]
 [11  9  1 12  2  9  1 11]
 [ 6  6  6  8  4 12  1  3]
 [13  7 10 12  6  3 14  1]
 [ 0  6  2 10 13  0 10  0]
 [15  9  4 13 13  5 13 11]]


In [ ]:
# Resize it to 6x6
A.resize(6,6)
print(A)
m,n = A.shape

[[ 7 10  9  2 14 11]
 [ 8  1  5  0  6  9]
 [ 3 11 15  8  1  7]
 [12  1  3 15  1 11]
 [11  9  1 12  2  9]
 [ 1 11  6  6  6  8]]


In [ ]:
# Apply Thresholding
t = 7    # int(input("Enter Threshold value: "))

B= np.zeros((m,n), dtype= np.int) 
for i in range(m):
  for j in range(n):
    if A[i,j]<t:
      B[i,j] = 1
    else:
      B[i,j] = 0

print(B)

[[0 0 0 1 0 0]
 [0 1 1 1 1 0]
 [1 0 0 0 1 0]
 [0 1 1 0 1 0]
 [0 0 1 0 1 0]
 [1 0 1 1 1 0]]


# Task 3

In [ ]:
# Create random 6x6 matrix
x = 6
y = 6
A = np.random.randint(0,16,size=(x,y))
print(A)

[[ 7  7  9  4  1  5]
 [10 12  3  3  5 11]
 [ 4  3 10  9 10 13]
 [11  4  1  0  2 10]
 [ 7  2  7  9  3  3]
 [ 1 10 12 14 11 10]]


In [ ]:
# Downsample by factor of 3
f = 3  

B =np.zeros((x//f,y//f),dtype=np.int)

for i in range(0,x,f):
  for j in range(0,y,f):
    try:
      B[i//f][j//f] = A[i][j]
    except IndexError:
      pass

x1,y1 = B.shape
print(x1, y1)
print(B)

2 2
[[ 7  4]
 [11  0]]


In [ ]:
f = 4
C=np.zeros((8,8),dtype=np.int)  # 2x2 upscaled will be 8x8 matrix

for i in range(0, 8-1, f):
  for j in range(0, 8-1, f):
    C[i,j]=B[i//f][j//f]


print(C)
m,n = C.shape

[[ 7  0  0  0  4  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [11  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


In [ ]:
#Replication Rows
for i in range(1, m-1, f):
  for j in range(0, n-1):
    C[i,j]=C[i-1,j]

#Replication Columns
for i in range(0, m-1):
  for j in range(1, n-1, f):
    C[i,j]=C[i,j-1]

print(C)
print(C.shape)

[[ 7  7  0  0  4  4  0  0]
 [ 7  7  0  0  4  4  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [11 11  0  0  0  0  0  0]
 [11 11  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
(8, 8)
